### ISSUE TITLE
Import on radarr and sonarr on test is successful, but no message is received in Telegram (Standard version)

### ISSUE THREAD

**Issue by Croman12** [NiNiyas/Bettarr-Notifications#1]
I have been busy for a few hours now and i got both the grab scripts for Sonarr and Radarr working. For one reason however, the scripts for import do not work. They use the same config file as the scripts for grab, when I run the module it is succesful (Successfully sent notification to Telegram.), but I receive no messages. Beneath is a log file, but I'm not sure it is of any use. A read the readme for the tor version that the standard version needs updating, but since the grab scripts works, I thought it should work. Any help is appreciated.

EDIT: I changed the chat_id for privacy reasons, I don't use that one. :)

```
[2021-09-01 18:36:27,603] INFO - Could not fetch episode sample. Falling back to series poster.
[2021-09-01 18:36:27,703] INFO - Couldn't fetch episode overview. Falling back to series overview.
[2021-09-01 18:36:27,774] INFO - {
    "chat_id": "-123456789",
    "parse_mode": "HTML",
    "reply_markup": {
        "inline_keyboard": [
            [
                {
                    "text": "View Series on Sonarr",
                    "url": "http://localhost:8989series/the-simpsons"
                },
                {
                    "text": "Open Sonarr",
                    "url": "http://localhost:8989"
                }
            ]
        ]
    },
    "text": "New episode downloaded - <b>None</b>: <i>SNoneENone</i> - <b>None</b>\n\n<b>Overview</b>\nSet in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.\n\n<b>Episode</b> - SNoneENone\n<b>Quality</b> - None\n<b>Content Rating</b> - TV-PG\n<b>Upgraded?</b> - No\n<b>Genre</b> - Animation, Comedy\n<b>Network</b> - Disney+\n<b>Release Name</b> - None\n<a href='https://artworks.thetvdb.com/banners/graphical/71663-g13.jpg'>&#8204;</a>"
}

```

**Comment by NiNiyas** [comment]
Hi. Thanks for using the script! Can you change 'http://localhost:8989/' to 'http://lan_ip:8989/' and try again? Because when I tested with localhost, I also didn't get the test notification. Don't forget the trailing '/' at the end.

**Comment by Croman12** [comment]
Don't ask me why, but after I changed localhost to local ip they are both working fine indeed. Weird though that localhost worked for the grab scripts and not for the download scripts. Thanks, anyway!
